# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicIOS-tutorial-ProjectTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ProjectTemplate
  pod 'Alamofire', '~> 5.2'

  # Pods for BasicIOS-tutorial-ProjectTemplate

  target 'BasicIOS-tutorial-ProjectTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BasicIOS-tutorial-ProjectTemplateUITests' do
    # Pods for testing
  end

end
